[package]
name = "shot"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
error-iter = "0.4.1"
log = "0.4.29"
nalgebra = "0.34.1"
pixels = "0.15.0"
winit = "0.30.12"
winit_input_helper = "0.17.0"
